### ISSUE TITLE
Can I specify sample points when envBlock is done on covariates?

### ISSUE THREAD

**Issue by immaryw** [rvalavi/blockCV#11]
Hi,

Based on my understanding of the function "envBlock", it allows us to use the parameter "rasterBlock" specify cluster on covariates or species data. When clustering is done on covariates, it is based on a certain number (defined by param "sampleNumber") of randomly sampled points from raster layers. 

Is it possible to build clusters based on a rasterstack of covariates **but from pre-defined sample points that have the same coordinates with the species data**? I have presence-absence data points and just want to do clustering on covariates of those points. 

Thanks!

**Comment by rvalavi** [comment]
Hi @immaryw 

Thanks for your comment.
Well, that's pretty easy! You only need to set `rasterBlock = FALSE`, then the clustering will be done only on the raster values on the location of the points i.e. values are extracted then clustering is done!

Cheers,
Roozbeh

**Comment by immaryw** [comment]
Thanks for your clarification! 

I thought `rasterBlock=FALSE`  made clusters based on response values of species data. I know I misunderstood that now.

Best,

Jing

**Comment by rvalavi** [comment]
My pleasure! No, it is based on the raster values on the point!

Cheers,
Roozbeh
