### ISSUE TITLE
rsample functions for spatial data

### ISSUE THREAD

**Issue by topepo** [rvalavi/blockCV#15]
The tidymodels group at RStudio is working on adding some spatial methods to our infrastructure, starting with resampling methods. (https://www.tmwr.org and https://www.tidymodels.org/start/resampling are good primers if you've never seen anything on tidymodels). 

We already have a PR for spatial resampling using clustering (tidymodels/rsample#185) and would probably create one using `blockCV`. Since you have a `sf` dependency, we probably wouldn't add that to `rsample`.

Would you be interested in having those tidymodels functions reside in `blockCV`? It would mean an `rsample` dependency.

**Comment by rvalavi** [comment]
Old comment!
