### ISSUE TITLE
spatialAutoRange does not seem to be working properly for unprojected rasters

### ISSUE THREAD

**Issue by ptitle** [rvalavi/blockCV#2]
I find that if I provide an unprojected raster to spatialAutoRange(), it finds one enormous block. I think this is incorrect.

```
> library(blockCV)
Loading required package: ggplot2
library(raster)

clim <- raster('CHELSA_bio_1.tif')

> library(raster)
Loading required package: sp
> 
> clim <- raster('CHELSA_bio_1.tif')
> clim
class       : RasterLayer 
dimensions  : 1766, 2287, 4038842  (nrow, ncol, ncell)
resolution  : 0.03333333, 0.03333333  (x, y)
extent      : -156.9918, -80.75847, 7.783194, 66.64986  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 
data source : /Users/pascaltitle/Dropbox/jays/predictors/coarse/CHELSA_bio_1.tif 
names       : CHELSA_bio_1 
values      : -282.1801, 287.2881  (min, max)

> 
> q <- spatialAutoRange(clim)
Loading required namespace: rgeos
Regions defined for each Polygons

> q$range
[1] 282386138
```
![screen shot 2019-02-21 at 11 37 04](https://user-images.githubusercontent.com/5825910/53185467-13e73c80-35cd-11e9-8586-7e00840034a7.png)

**Comment by rvalavi** [comment]
Hi @ptitle 

Thanks for reporting this. Have you had a look at the fitted variogram model?
If possible could you send me your raster data for further checking?

Thanks,
Roozbeh
email: rvalavi@student.unimelb.edu.au

**Comment by rvalavi** [comment]
Dear @ptitle 
Indeed the problem is because of the nature of your data. If you have a look at the variogram model of your layer (the following figure that quantifies the structure of spatial autocorrelation of your layer), it does not flat out and the range cannot be identified!
I recommend you to choose the block size based on other methods e.g. the range of spatial autocorrelation of your model residual. As mentioned in the associated paper the spatialAutoRange is not an absolute solution to choosing block size!

![image](https://user-images.githubusercontent.com/30306220/53374757-6e0d4680-39ad-11e9-9b0d-7e1c7a420fdd.png)

**Comment by ptitle** [comment]
Following your suggestion, I generated a correlogram to estimate at what distance spatial autocorrelation drops to zero, and then used that distance for producing spatial blocks. 

```
# sample a set of points across the raster and generate correlogram
dat <- as.data.frame(coordinates(bio1))
dat <- cbind.data.frame(dat, val = values(bio1))
dat <- dat[complete.cases(dat),]
dat <- dat[sample(1:nrow(dat), 10000),]

co1 <- ncf::correlog(dat$x, dat$y,dat$val, increment = 1, resamp = 0, latlon = T, na.rm=TRUE)
plot(co1$mean.of.class, co1$correlation, type='b', cex=0.5, ylab='correlation', xlab='distance class')
abline(h=0, lty=3)
abline(v=co1$x.intercept, lty=3)

# the dotted vertical line shows where spatial autocorrelation = 0.
zeroSA <- co1$x.intercept #in kilometers
```
<img width="550" alt="screen shot 2019-03-06 at 10 44 16" src="https://user-images.githubusercontent.com/5825910/53894056-6842e100-3ffd-11e9-99f1-85c8ffed75d0.png">

```
folds <- spatialBlock(PA, rasterLayer=bio1, theRange=zeroSA*1000, k=5, biomod2Format=F)
```
Using that distance for `spatialBlock()`, I get the following:

<img width="848" alt="screen shot 2019-03-06 at 10 48 05" src="https://user-images.githubusercontent.com/5825910/53894170-a0e2ba80-3ffd-11e9-91eb-a9239a7eff7b.png">

**Comment by rvalavi** [comment]
Hi @ptitle 
Sorry for the late response. I do not receive any warning for a message if you do not mention me in the message.
Well, this is still the spatial autocorrelation in the predictor raster. If you have presence-absence data, you can fit a simple model like a GLM, calculate the residuals and check the spatial autocorrelation in the residuals (e.g. with your correlogram).

I recommend having a look at Roberts et al., 2017, Cross-validation strategies for data with temporal, spatial, hierarchical, or phylogenetic structure, Ecography. There are good recommendation and background about the impacts of spatial autocorrelation on model evaluation.
