### ISSUE TITLE
implement terra 'SpatRaster' and 'SpatVector' inputs

### ISSUE THREAD

**Issue by AMBarbosa** [rvalavi/blockCV#20]
Hi, the 'terra' package is becoming increasingly used, as it replaces both 'raster' and 'sp'+'rgdal' and makes everything much faster. Would you be willing to implement the 'SpatRaster' and 'SpatVector' input formats too? In my experience, transition from 'sp'+'raster' was quite easy, and I've already implemented it in my own packages. Cheers!

**Comment by rvalavi** [comment]
Hi @AMBarbosa 
Thanks for the recommendation. I've already moved to `terra` in my own codes but haven't implemented it here. I'll move to `terra` as soon as I have some time. The major update (`v2.0`) was moving away from `sp` to `sf`. Replacing `raster` with `terra` should be relatively easy.

**Comment by rvalavi** [comment]
I'll keep this issue open until the updating process is doen!

**Comment by AMBarbosa** [comment]
Cool, thanks! Please remember to implement also 'SpatVector', as it is a sound and simple alternative to 'sf' that many users prefer.

**Comment by rvalavi** [comment]
Good news! `blockCV` is no update with all raster operations in `terra` and `sf`.
