### ISSUE TITLE
`spatialBlock` outdated 'scale' argument for ggplot2::guides

### ISSUE THREAD

**Issue by AMBarbosa** [rvalavi/blockCV#25]
Dear Roozbeh,
Running `spatialBlock()` with all packages at their latest CRAN versions, I now get:
```
Warning messages:
1: The `<scale>` argument of `guides()` cannot be `FALSE`. Use
"none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the blockCV
  package.
  Please report the issue to the authors.

This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this
warning was generated. 
```
Running `lifecycle::last_lifecycle_warnings()`, I get:
```
[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use
"none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the blockCV
  package.
  Please report the issue to the authors.
---
Backtrace:
 1. blockCV::spatialBlock(...)
 2. ggplot2::guides(fill = FALSE)
 3. ggplot2:::deprecate_warn0("3.3.4", "guides(`<scale>` = 'cannot be `FALSE`. Use \"none\" instead')")
```
Cheers,

**Comment by rvalavi** [comment]
Dear @AMBarbosa thank you so much for the report (and the previous ones). I'm working on `blockCV` right now, trying to resolve all these issues and release `v3.0  with many changes including using `terra` (with support for `starts` and `raster` objects); adding hexagon blocks (now, default), adding spatial cluster (xy cluster) and some other feature. I try to finish in the next few days. Any issue report on the new version is very much appreciated.

**Comment by AMBarbosa** [comment]
Cool, I'll move to v3.0 when it comes out! And since you're adding support for 'terra', it would be great if you'd include not just class SpatRaster, but also SpatVector (as an alternative to sf) for vector map inputs. Cheers!

**Comment by rvalavi** [comment]
Thanks! The new version will take any vector data that is convertible to an `sf` object (`SpatVector` is one of them). For raster, it will even accept files on disk or anything that can be convertible to a `SpatRaster`.

**Comment by rvalavi** [comment]
blockCV is updated and this warning is resolved; I'm closing this issue!
