### ISSUE TITLE
`cv_block_size` is unusable for non-interactive processing

### ISSUE THREAD

**Issue by pat-s** [rvalavi/blockCV#30]
Hi @rvalavi 

The new version of `spatialBlock()`, i.e. `cv_block_size()` is not usable in third-party packages like {mlr3spatiotempcv} as it always returns a shiny app instead of a simple R object.
This is **complete blocker** for script-based/non-interactive workflows in general.

In my view, the function

- should have an argument `interactive` with FALSE/TRUE and a default to `FALSE`
- should allow passing all required inputs in the arguments without having to define some in the interactive shiny app

Would you consider changing the behavior?

NB: I haven't yet checked if the outputs are backwards-compatible with `spatialBlock` (are they?). I see almost all arguments have changed. If not, this would be a huge reproducibility issue and I would appreciate not removing the old `spatialBlock()` but just creating a new standalone function/method that lives alongside the old one.

**Comment by pat-s** [comment]
Just came across `cv_spatial()` which looks more like being the successor of `spatialBlock()` (given it's arguments) even though `cv_block_size()` is name-wise much closer.

**Comment by pat-s** [comment]
OK, `cv_spatial()` is what I was searching for :)

**Comment by rvalavi** [comment]
@pat-s yep! that is it.

The naming is used to other blocking methods; the new blocking functions are now: `cv_spatial`, `cv_cluster`, `cv_buffer`, and `cv_nndm`; 

Check https://github.com/rvalavi/blockCV#new-updates-of-the-version-30

For buffering (`cv_buffer()`) use `report = FALSE` to make it faster;
