### ISSUE TITLE
Exporting Blocks and its fold names as Shapefile

### ISSUE THREAD

**Issue by ozgurhsyndgn** [rvalavi/blockCV#46]
All my respect and appreciation for the package you've created,

I'm using the package in my thesis and want to have better visuals with a GIS layout.  I'm trying to export the blocks and it's id/fold name/numbers in it as a shapefile.

How can I export a cv_spatial object as a shapefile?  

I'm lacking with data manipulation a bit, thanks for your help in advance,

Best regards,

Huseyin

**Comment by rvalavi** [comment]
Hi @ozgurhsyndgn 

Thanks for your interest in `blockCV`.

You can use `your_cv_obj$blocks` to access the blocks. Then use the `sf` package to write it to a file e.g.:

```R
sf::st_write(your_cv_obj$blocks, "file_path.shp")
```

**Comment by ozgurhsyndgn** [comment]
Thank you Mr. Valavi, this is what I was looking for!

Kind Regards.
