### ISSUE TITLE
Biomod2 pseudoabsences and blockCV

### ISSUE THREAD

**Issue by amythor** [rvalavi/blockCV#49]
Hey blockCV community, 

I am not normally one to post on here but I am just wondering if it is possible to use the blockCV package to cross-validate SDMs created with biomod2 if you have used the biomod2 internal function to create pseudo absences? 

I seem to be running into a problem trying to do this as it is not accounting for the 5 pseudoabsence generation repetitions I have created. 

Any help is much appreciated!

**Comment by rvalavi** [comment]
Hi @amythor,

Unfortunately, at the moment, this is not possible unless the biomod developers incorporate blockCV internally (which, to my knowledge, they have not). If you want to use the internal pseudo-absence selection, you will need to utilize one of the spatial cross-validation methods provided by biomod itself.

I hope this helps.

**Comment by amythor** [comment]
Sounds good, thank you for your response!
