### ISSUE TITLE
presence-background with Maxent

### ISSUE THREAD

**Issue by carbonmetrics** [rvalavi/blockCV#5]
I am trying to use blockCV with dismo::maxent. 
The advantage of dismo for me is the integration with raster: I can directly plot both the model results and the prediction. 

I can't get blockCV to work with dismo::maxent, because the trainSet from blockCV generates a vector. In that case, dismo::maxent wants background data; the predictors and occurrence instances are not enough.

How can I get this to work (preferably with foreach in view of its parallel processing capabilities)?

**Comment by rvalavi** [comment]
You can use blockCV with any of the models in dismo.

The easiest way to do that is:
1. generate the background point in dismo
2. combine it with the presence points
3. extract the covariate values
4. use all the data (presence + background) in blockCV and generate folds
5. model the data with dismo::maxent like the other models I explained in the vignette

**Comment by carbonmetrics** [comment]
Thanks! I have be / will be in the field with limited comms, but will work through your recommendations.
