### ISSUE TITLE
Strange in plot

### ISSUE THREAD

**Issue by Cam-in** [rvalavi/blockCV#50]
Hi! Previously plotting the block, the background of the raster was really nice. Now, is all in line
![image](https://github.com/user-attachments/assets/a48510f5-535c-49de-8d23-7ac600c2361a)

Previously
![Nac con_SPATIAL_BLOCKS_with_random_fold_assigment](https://github.com/user-attachments/assets/e9f8b14c-1d0b-4dc1-ac7f-00559a6cb886)

My code:
sb <- blockCV::cv_spatial(pts2, #ocurrence
                              column = species_name,
                              r = pred.brick, #raster spatial
                              k = 5,
                              size = range.size,  #from autocorrelation
                              hexagon = FALSE,
                              selection = "random", # randomly grouping the folds
                              iteration = 100, # find evenly dispersed folds
                              biomod2 = TRUE, # creates a table format you can use in biomod
                              plot = TRUE)

Could you help me identifying how to improve the plot? ggplot2 is updated
Thanks

**Comment by rvalavi** [comment]
Hi @Cam-in, thanks for reporting the issue! I’ve fixed it. Just reinstall the package from GitHub with:
```r
remotes::install_github("rvalavi/blockCV", dependencies = TRUE)
```
You can now adjust the background image quality (resolution) with the `max_pixels` argument if needed.

Closing this issue now.
