### ISSUE TITLE
get error when running spatialBlock

### ISSUE THREAD

**Issue by immaryw** [rvalavi/blockCV#6]
Hi there,

I got an error "Error in `[[<-.data.frame`(`*tmp*`, i, value = c(5, 1, 5, 2, 1, 2, 4,  : 
  replacement has 51 rows, data has 52" when running the function spatialBlock. I did a simulation of 10 runs. The first two work well, but get this error in the third run. Do you have some thoughts?

Thanks!

**Comment by immaryw** [comment]
When I change the selection from "random" to "systematic", I get a similar error: "Error in data.frame(blocks = seq_len(nrowBlocks), folds = systematicNum(subBlocks,  : 
  arguments imply differing number of rows: 49, 50"

Traceback:
3: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
2: data.frame(blocks = seq_len(nrowBlocks), folds = systematicNum(subBlocks, 
       k))
1: spatialBlock(speciesData = even[[i]], theRange = range1[[i]], 
       k = 5, selection = "systematic", iteration = 100, xOffset = 0, 
       yOffset = 0, showBlocks = FALSE)

**Comment by rvalavi** [comment]
@immaryw thanks for the reporting the issue.
Could you please provide me with more information about your data or if you can give an example data I can more specifically check track the issue.

**Comment by immaryw** [comment]
@rvalavi I changed theRange argument and solved the problem. Thanks!
