### ISSUE TITLE
Is it possible to rotate the grid to maximize the coverage of the study area? 

### ISSUE THREAD

**Issue by plthompson** [rvalavi/blockCV#9]
Thanks for the great package. I was wondering if there is any way to rotate the grid so that it is not positioned north south. I have a study region that is roughly square and goes from the north west to the south east. When I apply your method, I get a lot of blocks on the edge of the region and only contain a few sample locations. If the grid were rotated, the blocks would contain a more even number of sample locations. 

Thank you.

**Comment by rvalavi** [comment]
@plthompson  thank you for your comment.
Sorry for the late response. I don't receive any notification for issues that I'm not tagged in.

You can shift the spatial block horizontally or vertically when using `theRange` argument in the `spatialBlock()` function, but there is no rotation option. I had that in mind, but it is not easy to implement. Although, I might add it in the near future.

**Solution for your problem:**
You can use user-defined polygons in the `spatialBlock()` function. You can create an initial block, then rotated it (if you have any trick to do that), then use it again in the function. But, I'm always happy to discuss. You can provide more information/visualisation of your study area here or through my email, so we might be able to find a solution.

Regards,
Roozbeh

**Comment by plthompson** [comment]
Hi @rvalavi,

Thanks for your response. I ended up rotating my extent and then applying the spatialBlock() function. 

Cheers,
Patrick

**Comment by rvalavi** [comment]
@plthompson excellent!
